### ISSUE TITLE
Docker not working on Rpi 3b

### ISSUE THREAD

**Issue by ZsZolee** [kind-0/nsecbunkerd#12]
Is it possible to make it compatible to run on a Rpi 3b?

Status: Downloaded newer image for pablof7z/nsecbunkerd:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
673af42b891db26f43d4dc9b9cf4e88fa197e2bc70c69c4ca0592bb1ed7ec05b

**Comment by ZsZolee** [comment]
I tried to run it with a docker platform emulator, but on Rpi3 I couldn't even run the first docker command (it just died at the first step). On Rpi4 (4GB), I got the following error:

$ docker exec -i nsecbunkerd npx prisma db push
/app/node_modules/prisma/build/index.js:10578
    var wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                       ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at ../../node_modules/.pnpm/@prisma+prisma-fmt-wasm@4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81/node_modules/@prisma/prisma-fmt-wasm/src/prisma_fmt_build.js (/app/node_modules/prisma/build/index.js:10578:24)
    at __require (/app/node_modules/prisma/build/index.js:14:50)
    at Object.<anonymous> (/app/node_modules/prisma/build/index.js:89317:38)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.9.0

**Comment by pablof7z** [comment]
`Out of memory`

🤷‍♂️ not much I can do about it 😅

**Comment by IngwiePhoenix** [comment]
Create a 1G swapfile and retry. RPi 3b's memory is smol. ;)
