### ISSUE TITLE
CJS Build failed

### ISSUE THREAD

**Issue by Krittanai2933** [kind-0/nsecbunkerd#17]
CJS Build failed
Error: Build failed with 1 error:
D:\buncker\node_modules\esbuild\lib\main.js:249:10: ERROR: "outdir" must be a string
  at failureErrorWithLog (D:\buncker\node_modules\esbuild\lib\main.js:1649:15)
  at D:\buncker\node_modules\esbuild\lib\main.js:963:16
  at responseCallbacks.<computed> (D:\buncker\node_modules\esbuild\lib\main.js:703:9)
  at handleIncomingPacket (D:\buncker\node_modules\esbuild\lib\main.js:762:9)
  at Socket.readFromStdout (D:\buncker\node_modules\esbuild\lib\main.js:679:7)
  at Socket.emit (node:events:513:28)
  at addChunk (node:internal/streams/readable:324:12)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at Readable.push (node:internal/streams/readable:234:10)
  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

I don't know why it have this error when I try to run npm run build

**Comment by Krittanai2933** [comment]
my node version is 18.15

**Comment by pablof7z** [comment]
can you try setting `outDir` to `outdir`? 🤷‍♂️ I don't have a windows machine
